version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    command: ["sh", "-c", "yarn install && yarn workspace server start"]